version: '3'

//这个应该在redis文件夹下面

services:
  master:
    image: redis
    container_name: redis-master
    //masterauth参数是副本集同步密码,如果部署哨兵模式，现在的master可能变成slave，所以也要带上密码
    command: redis-server --requirepass redis_pwd  --masterauth redis_pwd  
    ports:
      - 6380:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd