version: '3.5'
# https://cloud.seafile.com/published/seafile-manual-cn/docker/%E7%94%A8Docker%E9%83%A8%E7%BD%B2Seafile.md
#创建网桥 docker network create --driver overlay --attachable devops

services:
  seafile-mysql:
    image: registry.gmpsoft.net:8443/mirror/library/mariadb:10.5
    hostname: seafile-mysql
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=seafile@123.  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /home/seafile/mysqlData:/var/lib/mysql:rw
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --innodb-use-native-aio=0
    networks:
      - devops

  seafile-memcached:
    image: registry.gmpsoft.net:8443/mirror/library/memcached:1.5.6
    hostname: seafile-memcached
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - devops

  seafile-server:
    image: registry.gmpsoft.net:8443/mirror/seafileltd/seafile-mc:8.0.4
    hostname: seafile-server
    container_name: seafile-server
    ports:
      - "8500:80"
 #     - "8543:443"  # If https is enabled, cancel the comment.
    volumes:
      - /home/seafile/seafile-data:/shared # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=seafile@123.  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=admin # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=seafile@123.     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
#      - SEAFILE_SERVER_HOSTNAME=seafile.gmpsoft.net # Specifies your host name.
      - SEAFILE_SERVER_HOSTNAME=seafile.gmpsoft.net
    depends_on:
      - seafile-mysql
      - seafile-memcached
    networks:
      - devops

networks:
  devops:
    external: true
    name: devops

