version: '3'
services: #服务配置
  redis-sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentine-1.conf 
    volumes:
      - ./sentinel-1.conf:/usr/local/etc/redis/sentine-1.conf #这个文件是哨兵文件，需要创建好后映射进容器里面。注意一个哨兵用一个文件
  redis-sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - 26382:26379
    command: redis-sentinel /usr/local/etc/redis/sentine-2.conf
    volumes:
      - ./sentinel-2.conf:/usr/local/etc/redis/sentine-2.conf
  redis-sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - 26383:26379
    command: redis-sentinel /usr/local/etc/redis/sentine-3.conf
    volumes:
      - ./sentinel-3.conf:/usr/local/etc/redis/sentine-3.conf
      
networks: #网络配置
  default:
    external:
      name: redis_default