version: '3'

#这个应该在redis文件夹下面

services:
  redis-master:
    image: redis
    container_name: redis-master
    #masterauth参数是副本集同步密码,如果部署哨兵模式，现在的master可能变成slave，所以也要带上密码
    command: redis-server --requirepass redis_pwd  --masterauth redis_pwd  --save ""
    ports:
      - 6380:6379
      
  redis-slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command: redis-server --replicaof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd   --save ""  #slaveof
    depends_on:
      - redis-master
    
  redis-slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --replicaof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd   --save ""
    depends_on:
      - redis-master
      - redis-slave1
    