version: '3.5'
# https://blog.csdn.net/weixin_47023868/article/details/111756503
#创建网桥 docker network create --driver overlay --attachable devops

services:
  redis: 
    image: registry.gmpsoft.net:8443/mirror/redis:6.2.1-alpine3.13
    hostname: redis
    ports:
      - 63790:6379
    volumes:
      - /home/jms/redis/data:/data:rw
#      - /home/jms/redis/redis.conf:/etc/redis.conf:rw
    
    command:
      redis-server --appendonly yes --requirepass jms@123.
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - devops
      
  mysql: 
    image: registry.gmpsoft.net:8443/mirror/mysql:8.0
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jms@123.
    ports:
      - 33060:3306
    volumes:
      - /home/jms/mysql/mysqlData:/var/lib/mysql:rw
      - /home/jms/mysql/mysql.cnf:/etc/mysql/my.cnf:rw
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --innodb-use-native-aio=0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - devops
     
  jumpserver: 
    image: registry.gmpsoft.net:8443/mirror/jumpserver/jms_all:v2.8.2
    hostname: jumpserver
    ports:
      - 8100:80
      - 22220:2222
    environment:
      - SECRET_KEY=x0kqBEQSYw4amYfSwQD8zUjGpvH5e3ADwooI9X853V8br1Z74y
      - BOOTSTRAP_TOKEN=JhP0YoHRiiNGkXej
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=jumpserver 
      - DB_PASSWORD=jms@123.
      - DB_NAME=jumpserver
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=jms@123.
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - devops
      
networks:
  devops:
    external: true
    name: devops

