version: '3.8'

services:
  localNginx: #服务名字
    image: nginx
    container_name: localNginx
    volumes: #卷配置 相当于配置硬盘
      - type: bind #安装类型 
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true #将卷设置为只读
        
    #depends_on: #表达服务之间的依赖性 配置后依赖docker提供的dns能力，可以访问如 rma-web:8080 rma-web:{动态端口} 一类的地址
      #- rma-web
    ports:
      - "8055:8055"
    environment: #设置容器内的环境变量 会覆盖镜像中的环境变量
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=8055