using System;
using System.Collections.Generic;

namespace Test.TrgitModels
{
    public partial class ApplicationSettings
    {
        public int Id { get; set; }
        public int? DefaultProjectsLimit { get; set; }
        public bool? SignupEnabled { get; set; }
        public bool? GravatarEnabled { get; set; }
        public string SignInText { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string HomePageUrl { get; set; }
        public int? DefaultBranchProtection { get; set; }
        public string RestrictedVisibilityLevels { get; set; }
        public bool? VersionCheckEnabled { get; set; }
        public int MaxAttachmentSize { get; set; }
        public int? DefaultProjectVisibility { get; set; }
        public int? DefaultSnippetVisibility { get; set; }
        public string DomainWhitelist { get; set; }
        public bool? UserOauthApplications { get; set; }
        public string AfterSignOutPath { get; set; }
        public int SessionExpireDelay { get; set; }
        public string ImportSources { get; set; }
        public string HelpPageText { get; set; }
        public string AdminNotificationEmail { get; set; }
        public bool? SharedRunnersEnabled { get; set; }
        public int MaxArtifactsSize { get; set; }
        public string RunnersRegistrationToken { get; set; }
        public bool? RecaptchaEnabled { get; set; }
        public string RecaptchaSiteKey { get; set; }
        public string RecaptchaPrivateKey { get; set; }
        public bool? RequireTwoFactorAuthentication { get; set; }
        public int? TwoFactorGracePeriod { get; set; }
        public bool? MetricsEnabled { get; set; }
        public string MetricsHost { get; set; }
        public int? MetricsPoolSize { get; set; }
        public int? MetricsTimeout { get; set; }
        public int? MetricsMethodCallThreshold { get; set; }
        public int? MetricsPort { get; set; }
        public bool? AkismetEnabled { get; set; }
        public string AkismetApiKey { get; set; }
        public int? MetricsSampleInterval { get; set; }
        public bool? SentryEnabled { get; set; }
        public string SentryDsn { get; set; }
        public bool? EmailAuthorInBody { get; set; }
        public int? DefaultGroupVisibility { get; set; }
        public bool? RepositoryChecksEnabled { get; set; }
        public string SharedRunnersText { get; set; }
        public int? MetricsPacketSize { get; set; }
        public string DisabledOauthSignInSources { get; set; }
        public string HealthCheckAccessToken { get; set; }
        public bool? SendUserConfirmationEmail { get; set; }
        public int? ContainerRegistryTokenExpireDelay { get; set; }
        public string AfterSignUpText { get; set; }
        public bool UserDefaultExternal { get; set; }
        public string RepositoryStorages { get; set; }
        public string EnabledGitAccessProtocol { get; set; }
        public bool? DomainBlacklistEnabled { get; set; }
        public string DomainBlacklist { get; set; }
        public bool? KodingEnabled { get; set; }
        public string KodingUrl { get; set; }
        public string SignInTextHtml { get; set; }
        public string HelpPageTextHtml { get; set; }
        public string SharedRunnersTextHtml { get; set; }
        public string AfterSignUpTextHtml { get; set; }
        public int MaxPagesSize { get; set; }
        public bool? UsagePingEnabled { get; set; }
        public bool? HousekeepingEnabled { get; set; }
        public bool? HousekeepingBitmapsEnabled { get; set; }
        public int HousekeepingIncrementalRepackPeriod { get; set; }
        public int HousekeepingFullRepackPeriod { get; set; }
        public int HousekeepingGcPeriod { get; set; }
        public bool? SidekiqThrottlingEnabled { get; set; }
        public string SidekiqThrottlingQueues { get; set; }
        public decimal? SidekiqThrottlingFactor { get; set; }
        public bool? HtmlEmailsEnabled { get; set; }
        public string PlantumlUrl { get; set; }
        public bool? PlantumlEnabled { get; set; }
        public int TerminalMaxSessionTime { get; set; }
        public int? UniqueIpsLimitPerUser { get; set; }
        public int? UniqueIpsLimitTimeWindow { get; set; }
        public bool UniqueIpsLimitEnabled { get; set; }
        public string DefaultArtifactsExpireIn { get; set; }
        public string Uuid { get; set; }
        public decimal PollingIntervalMultiplier { get; set; }
        public int? CachedMarkdownVersion { get; set; }
        public bool ClientsideSentryEnabled { get; set; }
        public string ClientsideSentryDsn { get; set; }
        public bool PrometheusMetricsEnabled { get; set; }
        public int RsaKeyRestriction { get; set; }
        public int DsaKeyRestriction { get; set; }
        public int EcdsaKeyRestriction { get; set; }
        public int Ed25519KeyRestriction { get; set; }
        public bool? AuthorizedKeysEnabled { get; set; }
        public bool? HelpPageHideCommercialContent { get; set; }
        public string HelpPageSupportUrl { get; set; }
        public int? PerformanceBarAllowedGroupId { get; set; }
        public bool HashedStorageEnabled { get; set; }
        public bool? ProjectExportEnabled { get; set; }
        public bool AutoDevopsEnabled { get; set; }
        public bool ThrottleUnauthenticatedEnabled { get; set; }
        public int ThrottleUnauthenticatedRequestsPerPeriod { get; set; }
        public int ThrottleUnauthenticatedPeriodInSeconds { get; set; }
        public bool ThrottleAuthenticatedApiEnabled { get; set; }
        public int ThrottleAuthenticatedApiRequestsPerPeriod { get; set; }
        public int ThrottleAuthenticatedApiPeriodInSeconds { get; set; }
        public bool ThrottleAuthenticatedWebEnabled { get; set; }
        public int ThrottleAuthenticatedWebRequestsPerPeriod { get; set; }
        public int ThrottleAuthenticatedWebPeriodInSeconds { get; set; }
        public int? CircuitbreakerFailureCountThreshold { get; set; }
        public int? CircuitbreakerFailureResetTime { get; set; }
        public int? CircuitbreakerStorageTimeout { get; set; }
        public int? CircuitbreakerAccessRetries { get; set; }
        public int GitalyTimeoutDefault { get; set; }
        public int GitalyTimeoutMedium { get; set; }
        public int GitalyTimeoutFast { get; set; }
        public bool? PasswordAuthenticationEnabledForWeb { get; set; }
        public bool? PasswordAuthenticationEnabledForGit { get; set; }
        public int CircuitbreakerCheckInterval { get; set; }
        public string AutoDevopsDomain { get; set; }
        public bool? PagesDomainVerificationEnabled { get; set; }
        public bool AllowLocalRequestsFromHooksAndServices { get; set; }
    }
}
